version: 1.0.0
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: ./Build/nuget/*.nupkg
  name: NuGet
